version: '3'

services:

#authentication

  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Belgrade
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - authenticationdbdata:/var/lib/mysql

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
      - TZ=Europe/Belgrade
    depends_on:
      authenticationDB:
        condition: service_healthy

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
      - TZ=Europe/Belgrade
    depends_on:
      - authenticationDBMigration
    ports:
      - 5000:5000


#elections

  electionsDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Belgrade
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3307:3306
    volumes:
      - electionsdbdata:/var/lib/mysql

  electionsDBMigration:
    image: electionsdbmigration
    environment:
      - DATABASE_URL=electionsDB
      - TZ=Europe/Belgrade
    depends_on:
      electionsDB:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - 6379:6379

  admin:
    image: admin
    environment:
      - DATABASE_URL=electionsDB
      - TZ=Europe/Belgrade
    depends_on:
      - electionsDBMigration
    ports:
      - 5001:5001

  votingStation:
    image: votingstation
    environment:
      - REDIS_HOST=redis
      - TZ=Europe/Belgrade
    depends_on:
      - redis
    ports:
      - 5002:5002

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=electionsDB
      - REDIS_HOST=redis
      - TZ=Europe/Belgrade
    depends_on:
      - redis

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  authenticationdbdata:
  electionsdbdata:
